---
language: 'python'
python:
  - '2.7'
  - '3.4'
  - '3.6'

before_install:
  - 'pip install setuptools flake8 pytest'

install:
  - 'pip install --editable .'

script:
  - 'flake8 .'
  - 'pytest ./tests/unit.py'
  - 'pytest ./tests/test_app_wp1/tests'
