---
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev

before_install:
  - pip install -r requirements/ci_common.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then pip install -r requirements/ci_modern.txt; fi

install:
  - pip install .

script:
  # run unit tests in all environments
  - pytest ./tests/unit.py ./tests/test_app_wp1/tests
  - mypy flask_webpack
  - black --check
